#!/bin/bash
# gsload - Given a list of GeoTIFFs as arguments, upload them to your GeoServer
#
# All filenames must match this example's format:
#    I      YYYYDDD              ANALYTIC........
# EO1A0640452014065110KC_ALI_L1G_CLASSIFIED_COLOR.tif,
#
# Usage:
# $ gsload [GEOTIFF]...
# For example,
# $ gsload mygeotiffs/*

gsdata=/var/lib/tomcat7/webapps/geoserver/data/data
workspace=eo1

sudo -u tomcat7 mkdir -p $gsdata/$workspace/

for file in "$@"; do
    name=`basename $file`

    if [ ${name:3:1} == 'A' ]; then
        instr=ali_l1g
    else
        instr=hyperion_l1g
    fi

    # Given EO1A0640452014065110KC_ALI_L1G_CLASSIFIED_COLOR.tif,
    # set analytic=CLASSIFIED_COLOR
    [[ $name =~ ([A-Z0-9]+_){3}(.+)\. ]] && analytic=${BASH_REMATCH[2]}

    yyyy=${name:10:4}
    ddd=${name:14:3}

    # Trick from http://superuser.com/a/232106
    month=`date -d "$yyyy-01-01 +$ddd days -1 day" "+%Y-%m"`

    location="$gsdata/$workspace/$instr/$analytic/$month/$name/"
    # Move files
    sudo -u tomcat7 mkdir -p "$location"
    sudo -u tomcat7 rsync "$file" "$location"
    # Upload files
    curl -u admin:geoserver -XPOST -H 'Content-Type: application/xml' -d "<coverageStore><name>$name</name><workspace>$workspace</workspace><enabled>true</enabled></coverageStore>" http://localhost:8080/geoserver/rest/workspaces/$workspace/coveragestores
    curl -u admin:geoserver -v -XPUT -H 'Content-type: text/plain' -d "file:$location" http://localhost:8080/geoserver/rest/workspaces/$workspace/coveragestores/$name/external.imagemosaic
done
